spring:
  application:
    name: consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: my-group
      properties:
        spring.json.use.type.headers: true


server:
  port: 0
